@TodoMicroSaas.Api_HostAddress = https://localhost:7059

POST {{TodoMicroSaas.Api_HostAddress}}/users/
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@example.com"
}

###
