@TodoMicroSaas.Api_HostAddress = https://localhost:7059

POST {{TodoMicroSaas.Api_HostAddress}}/users/
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@example.com"
}

###

POST {{TodoMicroSaas.Api_HostAddress}}/checkout/
x-user-id: 09fd4558-4805-49d3-8ad3-44053c65d763

###

GET {{TodoMicroSaas.Api_HostAddress}}/success/

###

POST {{TodoMicroSaas.Api_HostAddress}}/todos
Content-Type: application/json
x-user-id: 09fd4558-4805-49d3-8ad3-44053c65d763

{
    "description": "Test Todo 6 User 2"
}




