@TodoMicroSaas.Api_HostAddress = https://localhost:7059

POST {{TodoMicroSaas.Api_HostAddress}}/users/
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@example.com"
}

###

GET {{TodoMicroSaas.Api_HostAddress}}/checkout/
x-user-id: 25d5f984-fe4b-497d-bf8a-92ded623117d

###

GET {{TodoMicroSaas.Api_HostAddress}}/success/


